default:
  server:
    port: 3000
  database:
    host: 'localhost'
    schema: "data"
  elastic:
    host: localhost
    port: 9200
    allowedIndexes:
      - data_rasters
      - data_states
development:
  database:
    db: 'dev_db'
test:
  database:
    db: 'test_db'
production:
  server:
    port: 8000
  database:
    db: 'prod_db'
    user: 'dbuser'
  cache:
    dir: 'static'
