default:
  server:
    port: 3000
  database:
    host: 'SDB312PD'
    schema: "svc_sgagsservices"
  elastic:
    host: localhost
    port: 9200
    allowedIndexes:
      - isi_data_rasters
      - isi_data_states
      - isi_data_sites
development:
  database:
    db: 'dev_db'
test:
  database:
    db: 'test_db'
production:
  server:
    port: 8000
  database:
    db: 'prod_db'
    user: 'dbuser'
    password: 'pass'
  cache:
    dir: 'static'